spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_account?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password: password

    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3307/user_account?useSSL=false&serverTimezone=Asia/Seoul
          username: root
          password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

